"""Criação das tabelas

Revision ID: 0b2f4669ce76
Revises: bc8ac199c58c
Create Date: 2025-05-29 13:18:26.048330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b2f4669ce76'
down_revision: Union[str, None] = 'bc8ac199c58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiais', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'materiais', 'projetos', ['projeto_id'], ['id'])
    op.drop_column('materiais', 'projeto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiais', sa.Column('projeto', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'materiais', type_='foreignkey')
    op.drop_column('materiais', 'projeto_id')
    # ### end Alembic commands ###
