"""Criação das tabelas

Revision ID: 40a2101005e8
Revises: b6af96c83f86
Create Date: 2025-05-30 22:27:14.607004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40a2101005e8'
down_revision: Union[str, None] = 'b6af96c83f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'projetos', ['projeto_id'], ['id'])
    op.drop_column('clientes', 'projeto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('projeto', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'projeto_id')
    # ### end Alembic commands ###
