"""Criação das tabelas

Revision ID: b6af96c83f86
Revises: 0b2f4669ce76
Create Date: 2025-05-29 16:00:54.989277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6af96c83f86'
down_revision: Union[str, None] = '0b2f4669ce76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'funcionarios', 'projetos', ['projeto_id'], ['id'])
    op.drop_column('projetos', 'responsavel_projeto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('responsavel_projeto', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'funcionarios', type_='foreignkey')
    op.drop_column('funcionarios', 'projeto_id')
    # ### end Alembic commands ###
