"""Criação das tabelas

Revision ID: bc8ac199c58c
Revises: 
Create Date: 2025-05-27 10:47:30.641050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8ac199c58c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('projeto', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.String(length=100), nullable=False),
    sa.Column('tipo_material', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('unidade_medida', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('fornecedor', sa.String(length=100), nullable=False),
    sa.Column('projeto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_id'), 'materiais', ['id'], unique=False)
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.String(length=50), nullable=False),
    sa.Column('data_fim', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('custo_total', sa.Float(), nullable=False),
    sa.Column('custo_atual', sa.Float(), nullable=False),
    sa.Column('progresso', sa.Float(), nullable=False),
    sa.Column('responsavel_projeto', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_table('projetos')
    op.drop_index(op.f('ix_materiais_id'), table_name='materiais')
    op.drop_table('materiais')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
